### ISSUE TITLE
Xbox Live Profile doesn't get generated anymore.

### ISSUE THREAD

**Issue by ghost** [xenia-canary/xenia-canary#108]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Since updating the last days ago xenia canary (also tested non canary builds) is not generating an Xbox Live Profile anymore. I tried everything described here [Github Xenia Profiles](https://github.com/xenia-canary/xenia-canary/wiki/Profiles) but [E000-filename].dir is never generated in any circumstances. I also deleted everything and tried a brand new folder - still no profile gets generated.

It's really weird because I was able to play for example _Rayman Legends_ _Challenges_ (which require a Xbox Live Profile) and after updating I got the error message "_A profile signed-in to the Xbox LIVE is required to access this feature_".  The profile problem is not game specific I just state Rayman Legends as an example!

I tried to track down the specific built that was last working but I couldn't.

Is this problem known? I only found someone on reddit stating its controller related but I doubt that because I removed the canary folder totally, used a new folder path and a fresh download. That generated all required files like e.g. xenia-canary.config.toml but still no profile - I obviously started some games to make sure the profile creation is not deferred to a later stage. 

Is this problem known?

Are there maybe hidden paths I don't know about that need to be deleted?

I deleted so far:
- the xenia-canary folder (which seems to work as portable now out of the box)
- the user/Documents/Xenia folder (which doesn't seem to be used by xenia-canary anyway but just to be sure i deleted it also)

Still no profile gets generated. If it helps I can provide a Screenrecording of the process. Whatever I can do to help - please let me know.

### Describe what should happen

XeniaUser0 or XeniaUser should be generated. Or when providing a specific profile (i used velocity to generate one) it should use the profile saved in the content folder (Content\FFFE07D1\00000001\) and then generate a [E000-filename].dir folder **which never happens.**

**Comment by j4wassup** [comment]
vouch

**Comment by ghost** [comment]
@emeraldongithub 

vouch means you have the same problem?

**Comment by j4wassup** [comment]
Yes.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SeventySixx** [comment]
Same problem here.

I tried also to create manually the folders structure FFFE07D1\00000001 and put there the profile file.

in the config file I couldn't find the section [profiles], so I created it manually adding the reference to the profile file. 
Starting a game it cleaned up the config file by removing the added section and didn't worked.

**Comment by j4wassup** [comment]
They really had one job and failed..


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Gliniak** [comment]
Feature of manual profiles was removed due to certain issues. It will be back in the future.
HOWEVER. Xenia creates "virtual" profile/profiles while you're starting it or when you connect controller.

In simple terms: It's not required from user to create their own profile it is done under the hood. 
If game asks for it that means something is wrong with that game or more likely something is wrong with controller visibility. It might not see it as being connected to slot 0

**Comment by SeventySixx** [comment]
@Gliniak Thanks for your answer. Mine was a superficial problem, in games like Forza Horizon 2 the "in game" username it's read directly from the profile, so you will have a generic "User", and it seems there isn't a way to overwrite it, if not defining it in a manual profile. Beside this, the game work flawless.

**Comment by Gliniak** [comment]
With Forza games there is another issue. 
If you want something like profile right now you can use PR build:
https://github.com/xenia-canary/xenia-canary/pull/120 or 
https://github.com/xenia-canary/xenia-canary/pull/118

One will allow to just change username (that 118) another one creates different directories and generates unique xuid based on username

**Comment by ghost** [comment]
> Feature of manual profiles was removed due to certain issues. It will be back in the future. HOWEVER. Xenia creates "virtual" profile/profiles while you're starting it or when you connect controller.

I am pretty sure nobody here wants to fiddle with manual profiles. Like me, the others tried everything they could find online to somehow get a profile to work. There is definitely something you guys have not seen yet. Since posting the first time i download every new release in the hope it maybe some weird issue but it just won't go away. It's weird because many months ago xenia was generating a profile succesfully for me. I remember playing Rayman Legends Challanges AND since months i can't play them because i get a message that i need a profile. 

> In simple terms: It's not required from user to create their own profile it is done under the hood. If game asks for it that means something is wrong with that game or more likely something is wrong with controller visibility. It might not see it as being connected to slot 0

Regarding "somethign wrong with the game": I tried multiple games and they all have the same problem. I can assure you it's not a singular game issue.

Regarding the "controller": I use two original Xbox Series X controllers - no success. I even tried just now Xoutput (a virtual Xbox 360 controller emulator)  just in case it would have problems with modern controllers (i know that makes little sense - anyway Xbo 360 controllers are also not working.

**I don't want to somehow sounds like a pushy asshole, i just want you to know that it's definitely not some kind of user error from our side. I tested for hours to be sure it's not on my side.** 

I am on Win11 but others seem to have issues with Win10. Could maybe something have changed with later updates in Windows10/11 that Xenia somehow relies on? Maybe some library?

Thanks for all you guys are doing. If i can somehow help with narrowing down the problem please let me know.

**Comment by r3538987** [comment]
If this is ongoing topic, any info in which older version works as it should?, with proper Profile creation and Save file reading for XBLA games in example.

**Comment by TRexIndominus** [comment]
I hope they bring back this feature.

**Comment by loslover** [comment]
im having the same problem as it wont generate a profile so i cant save inside of the game im wanting to play sonic the hedgehog (2006) with the mod legacy of solaris

**Comment by SkyHighGam3r** [comment]
Hoping this comes back at some point. 
I can't access the offline portion of the multiplayer in Ghostbusters.

**Comment by emptyinside666** [comment]
I've ran into this 3 times in 24 hours so there is nothing "under the hood" apparently and this has been an issue for over a year and a half so reintroduction of the previous working system seems not to be a goal.  No coder/hacker folks have figured out a loophole to bypass the check or fix the old profile system?  I'm a musician so I'm of no help there but if you need a song written to express your rage, I got you!  Haha.

**Comment by MisterAIDSRat** [comment]
vouch
imagine being so unbelievably braindead that you remove this feature for no discernable reason
sucks that xenia-canary is the only decent nightly fork of xenia because this is maddening

**Comment by Gliniak** [comment]
Let me write that once more why it was removed from canary.

It wasn't fully functional and was in a long term causing issues.
Why it wasn't fully functional?
1. It was extracting profile internal files from console profile package (if provided) and write directly to extracted files. This causes issues, because you wouldn't be able to use that profile back on console without some heavy shenanigans.
2. I couldn't just swap it to use make it use stfs like for savefiles, because after specific point profile would get corrupted.
3. About STFS point above that it can get corrupted + it wasn't reflecting really how it works on console and was writing incorrect data in few spots.
4. Code had maintainability issues which was big pain in the ass for me as it took me way too many hours to understand.

Most of your issues when game reports that there is no profile available is caused by incorrect controller assignment. 
Sometimes controller can switch from slot 0 where default profile is available to 1 where there is nothing. 
Less common situation is when there is an emulation bug that causes detection failure.

Thanks to that previous message I'm locking this thread.
This feature will come back as soon as STFS implementation is done (or shortly after), so please be patient. Sadly there is no dedicated team in this project that can fix everything in days.
