### ISSUE TITLE
Bug on Ninja Gaiden 2 at Dual Armadilos level game crash at level

### ISSUE THREAD

**Issue by dimaabull** [xenia-canary/xenia-canary#109]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Ninja gaiden 2 crash at chapter 13 after the dual armadilos boss fight

### Describe what should happen

The level should run okay and cutscenes

### If applicable, provide a callstack here, especially for crashes

Probably hás something tô do with that second dragon save

**Comment by Margen67** [comment]
Does this happen on master?
