### ISSUE TITLE
CRASH ANY GAMES D3D12  (7900 xtx )

### ISSUE THREAD

**Issue by FOOTGRICK** [xenia-canary/xenia-canary#129]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

![image](https://user-images.githubusercontent.com/125401398/218835916-03bbfd84-4da1-42c3-be1c-1d8c6a7b4f02.png)
![image](https://user-images.githubusercontent.com/125401398/218836065-4f14960d-027e-45f8-ab7d-083a8f3f146e.png)

### Describe what should happen

when launch any games with d3d12 .... vulkan work 
on 7900 xtx 

### If applicable, provide a callstack here, especially for crashes

![image](https://user-images.githubusercontent.com/125401398/218836065-4f14960d-027e-45f8-ab7d-083a8f3f146e.png)

### If applicable, upload a logfile and link it here

![image](https://user-images.githubusercontent.com/125401398/218836065-4f14960d-027e-45f8-ab7d-083a8f3f146e.png)

**Comment by Gliniak** [comment]
There is probably a bug in AMD drivers which causes this issue. 
You can set: ``d3d12_remove_retc_from_geometry_shader = true``, but it might freeze or hardlock your PC, so we take no responsibility for any data loss.

**Comment by FOOTGRICK** [comment]
thks for your response do you think in futur driver will be solve this issue ? 
tested with your setting , same error

**Comment by Gliniak** [comment]
Might be but that is probably up to AMD
