### ISSUE TITLE
Xenia Canary build from 17th February 2023 crashed with unoccured exception when leaving to main menu in RDR1

### ISSUE THREAD

**Issue by Krokx** [xenia-canary/xenia-canary#135]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

When exiting in Read Dead Redemption GOTY from the game menu to the main menu, when trying to confirm (pressing A) Xenia Canary crashes with an unoccured exception.

### Describe what should happen

The game should go back to the main menu instead of crashing.

### If applicable, provide a callstack here, especially for crashes

Sorry don't know what a callstack is.

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/10845509/xenia.log)

**Comment by AdrianCassar** [comment]
The log says that the game tried to relaunch itself, this causes a XEX swap and isn't yet supported by Xenia. A crash is expected whenever a XEX swap occurs.

**Comment by Krokx** [comment]
Thanks for answering. It's not game braking since I can exit by simply closing the window. But besides this the latest build works very good with RDR1. I can play seamlessly. From time to time a short stutter of audio occurs, but it disappears after a few seconds, so this also is not game braking. Thank you for making it possible playing RDR1 on PC, something I wanted to, for a very long time.

**Comment by Margen67** [comment]
Does this happen on master?
