### ISSUE TITLE
Launching a Xex from inside another Xex not working as intended

### ISSUE THREAD

**Issue by jnackmclain** [xenia-canary/xenia-canary#141]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

This is a small rabbit hole so bear with me.

There is a demo disc that is a combo demo disc for "The Beatles Rock Band" and "Rock Band 2" (454188B2). How this disc works is in the root, there is a default.xex. This is a loader xex which only functions to allow the user to choose which demo to load. These demos are located within subfolders inside the demo disc files as shown. proj9 is the beatles demo, band2 is rock band 2.

![image](https://user-images.githubusercontent.com/55568980/223763135-87151603-f680-4d7d-8d92-9ed99778adba.png)

In xenia, the loader functions, but trying to boot into the sub game crashes with a disc read error.

![image](https://user-images.githubusercontent.com/55568980/223763399-1a62d81b-b73f-40ae-b096-35dc78da9840.png)

However, I have found via modding the loader, that launching forwarded xex files is actually supported in xenia, but something is going wrong. I can edit the calls in the game's scripting to boot a default.xex located in the root, next to the loader xex, and boot any game I like, I only have problems using it's original functionality to launch a game stored in a subfolder. This modified functionality also is verified working on original console, as is the original demo functionality. The loader's scripting allows you to specify the directory containing another default.xex. if you pass that script '', it will load the default.xex stored in the root.

For my project, I would love to have access to the ability to run from sub-folders, and if this combo demo loader functionality gets fixed, so should what I'm working on.

### Describe what should happen

The combo demo loader should be able to launch a default.xex stored in a subfolder.

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/10922781/xenia.log)

**Comment by Margen67** [comment]
https://github.com/xenia-project/xenia/issues/1228
https://github.com/xenia-project/xenia/issues/665
