### ISSUE TITLE
Unhandled Exception In Xenia

### ISSUE THREAD

**Issue by NICKMANKOK** [xenia-canary/xenia-canary#143]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

when i opened this application it shows code like this

### Describe what should happen

![Screenshot (83)](https://user-images.githubusercontent.com/128476298/226588015-a7a57830-2fa5-4441-8baf-81d34c01456d.png)

after that this app not responding and crashes evrytime

### If applicable, provide a callstack here, especially for crashes

Exception encountered!

Build: canary_experimental@8678becda on Mar 13 2023 
Exception address: nvwgf2umx.dll+91C9A8 
Stackpointer: 0xA0A4D8AEDO
Instruction pointer : nvwgf2umx.dll+91C9A8
ExceptionCode: 0x3221225477 (The instruction at Ox%p referenced memory at Ox%p. The memory could not be %s)
Last NTSTATUS: 0xC0000023 ((Buffer Too Small) The buffer is too small to contain the entry. No information has been
written to the buffer)
Last errno value Ox2: (no such file or directory)
Faulting thread name :

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/11027580/xenia.log)
[xenia.log](https://github.com/xenia-canary/xenia-canary/files/11027587/xenia.log)

**Comment by WesternSpace** [comment]
I have a similar error that occurs: 
![image](https://user-images.githubusercontent.com/80211714/229946204-5accbd0a-3faf-4ae7-8f1e-6028f9643af4.png)
[xenia.log](https://github.com/xenia-canary/xenia-canary/files/11153995/xenia.log)

In this case, it occurs is after launching RDR an only at the main menu.

**Comment by robbely** [comment]
> I have a similar error that occurs: ![image](https://user-images.githubusercontent.com/80211714/229946204-5accbd0a-3faf-4ae7-8f1e-6028f9643af4.png) [xenia.log](https://github.com/xenia-canary/xenia-canary/files/11153995/xenia.log)
> 
> In this case, it occurs is after launching RDR an only at the main menu.

I get this from within the game if I try to return to the main menu.

**Comment by steveosten2** [comment]
I am having this same issue after a few minutes playing forza horizon 
![Screenshot (3)](https://user-images.githubusercontent.com/91251086/232244707-80f0f4da-80cf-44cd-95ab-3310c82804ba.png)

**Comment by Pahlarity** [comment]
I have the same issue when I try and start the first race in FM4. 

![image](https://user-images.githubusercontent.com/131368493/233372562-648bfe6a-e398-4605-b24c-626292471197.png)

**Comment by robbely** [comment]
I'm pretty sure the Forza game issue is a separate one relating to the XMA decoder and should probably have its own thread.

With Red Dead, if I play the PS3 version (in its own emulator), when I go back to the main menu it seems to reset the emulated console in some way. Maybe the x360 version does the same thing and this "reset" isn't properly implemented in xenia?

**Comment by ikeboy783** [comment]
![image](https://user-images.githubusercontent.com/132864830/236721843-754776b3-13f2-4ccd-ae1d-54fe7bbb0e97.png)
i have the same problem
