### ISSUE TITLE
keyboard controls don't work

### ISSUE THREAD

**Issue by alectprasad** [xenia-canary/xenia-canary#15]
none of the controls as mentioned [here](https://github.com/xenia-canary/xenia-canary/blob/canary_new/src/xenia/hid/winkey/winkey_input_driver.cc) work.

**Comment by JoelLinn** [comment]
Set hid=“any” in the config file.

**Comment by CitroenGames** [comment]
it still doesnt workfor me i tried it and i noticed that before may 2020 it did work but now it doesnt and the diffrence are the name of the exe and older version does check for update and i get a popup newer version doesnt have that so i think something is wrong with the new version

**Comment by nanahcubamme** [comment]
i also set hid to any and was still unable to use keys for input

**Comment by Margen67** [comment]
Does this still occur, and if so, does it also occur on xenia master? @alectprasad @CitroenGames @nanahcubamme
