### ISSUE TITLE
Lags and Doesn't show some parts of the UI on some games.

### ISSUE THREAD

**Issue by Latancy** [xenia-canary/xenia-canary#152]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [x] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Latest build suddenly tanks performance on some multiple games such as Red Dead Redemption and Skate Series.
Also the UI for Skate 1 - 3 doesn't show. 
For example on Skate 3 when doing some challenges for the TWS/Thrasher magazine it doesn't show the final shot for the UI and shots taken doesn't show on the billboard.

### Describe what should happen

Optimize and fix the UI Issue. 

### If applicable, provide a callstack here, especially for crashes

-

### If applicable, upload a logfile and link it here

-

**Comment by Margen67** [comment]
Does this happen on master?
