### ISSUE TITLE
gta iv crash

### ISSUE THREAD

**Issue by JuanjoSevilla3** [xenia-canary/xenia-canary#155]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Good today I started gta iv and everything was going very well but at the end of the mission where I had to kill Roman's lender it crashes and gives me the following error error the gpu device has been lost

### Describe what should happen

what should happen is that you can finish the mission correctly

### If applicable, provide a callstack here, especially for crashes

crash

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/11301952/xenia.log)

**Comment by Margen67** [comment]
Does this happen on master?

**Comment by JuanjoSevilla3** [comment]
> ¿Esto sucede en el maestro?

does not occur in canary
