### ISSUE TITLE
Red Dead Redemption save file issues

### ISSUE THREAD

**Issue by jaldoyn** [xenia-canary/xenia-canary#18]
I downloaded the latest canary version and now the games fail to read or write to the content folder in fact even if I select to continue without saving the game freezes. I don't know if is an issue limited to this particular game, but since this is the only game I own I can't verify whether this is a global issue or not.

**Comment by Gliniak** [comment]
I wrote note on discord that there is a bug after merging new stuff. 
I hope you had savefiles in different slots that first, because now it is overwritten.

**Comment by jaldoyn** [comment]
> I wrote note on discord that there is a bug after merging new stuff.
> I hope you had savefiles in different slots that first, because now it is overwritten.

I'm glad I did. So for now should I stick to the master branch?
