### ISSUE TITLE
![image](https://user-images.githubusercontent.com/132864830/236721843-754776b3-13f2-4ccd-ae1d-54fe7bbb0e97.png)

### ISSUE THREAD

**Issue by bogdan1802-bit** [xenia-canary/xenia-canary#203]
![image](https://user-images.githubusercontent.com/132864830/236721843-754776b3-13f2-4ccd-ae1d-54fe7bbb0e97.png)
i have the same problem

_Originally posted by @ikeboy783 in https://github.com/xenia-canary/xenia-canary/issues/143#issuecomment-1537657480_

**Comment by Gliniak** [comment]
AMD driver fault, not Xenia. Update drivers.
