### ISSUE TITLE
Graphics device lost 


### ISSUE THREAD

**Issue by HYDRAEMPEROR1337** [xenia-canary/xenia-canary#209]
Graphics device lost (probably due to an internal error)
How to fix this issue sir please help my GPU rx6500 xt

**Comment by HYDRAEMPEROR1337** [comment]
> Graphics device lost (probably due to an internal error)
> How to fix the issue sir please help my GPU rx6500 xt 

Hello?

**Comment by Margen67** [comment]
Issues with the 6xxx series are expected.
