### ISSUE TITLE
Framerate of the game becomes capped to 60 FPS when Title Update applied

### ISSUE THREAD

**Issue by Kyogre** [xenia-canary/xenia-canary#22]
When TU is not applied, the game (e.g. Gears of War 2) runs with uncapped framerate (not only in menu, but everywhere if PC's power is enough). I have 120hz monitor, so mine game runs in 120 FPS.
But after you apply TU the game becomes capped to 60 FPS.
Here is the video demonstration: https://youtu.be/XtwTMvimpwI

**Comment by illusionyy** [comment]
There hasn't been a patch made for TUs yet

**Comment by Kyogre** [comment]
Thank you for the clarification. Now I see that it is possible to [create patches for specific title update](https://github.com/xenia-canary/game-patches/issues/9#issuecomment-821830856).
