### ISSUE TITLE
Muchi Muchi Pork & Pink Sweets

### ISSUE THREAD

**Issue by MidnightBlueWolf** [xenia-canary/xenia-canary#231]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Black screen on loading game.

### Describe what should happen

Game screen should be visible on loading.

**Comment by neurodiverseEsoteric** [comment]
@MidnightBlueWolf Sorry nobody's attempted to be helpful until now; but if you're still around: Setting gpu_allow_invalid_fetch_constants=true inside xenia.config.toml (or xenia-canary.conig.toml), as per @bruce5's comment from a similar issue with DDPSDOJ ( https://github.com/xenia-project/game-compatibility/issues/438 ), also fixes this issue for me too (on an all-AMD Lenovo Legion Go+CachyOS+WINE, mind you)*. 

*(That got the game's graphics showing, but not the game playing, unfortunately. There's a crash/freeze upon attempting to select the "Muchi Muchi Pork" side for me, and I'm still trying to figure out where/how to report that...)

**Comment by Margen67** [comment]
GitHub isn’t for tech support.
