### ISSUE TITLE
545408BA - WWE 2K17: Freezes after match starting

### ISSUE THREAD

**Issue by VladOFF92** [xenia-canary/xenia-canary#235]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [ ] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [ ] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

When I start to play in WWE 2K17 on Xenia Canary, the game process goes perfectly - there is no any lags and bugs in menu, wrestlers' intros runs good. But **when the match starts, game freezes after gong** without crushing and nothing happens.

On the path of problem's deciding I **tried to**:
1. Use earlier (2021 and 2022) and newest (September-October) versions of Xenia Canary (I'm using version from August 8 for stable playing to other games usually)
2. Change settings in NVidia Control Panel "Adjust Image Settings with Preview" from "Quality" to "Performance"
3. Change "gpu" settings in xenia-canary.config from "gpu="d3d12"" to "gpu="vulkan"" (and back later)
4. Disable vsync in xenia-canary.config

Unfortunately, all of this ways **didn't help** to decide my problem.

And I wanna notice: this bug is typical for **every** WWE 2K games from WWE 2K12 to WWE 2K17.

### Describe what should happen

Help me to set my emulator for comfortable playing to WWE 2K17. Which settings of Xenia Canary I should use for stopping freezing?

### If applicable, provide a callstack here, especially for crashes

![wwe2k17_freezes](https://github.com/xenia-canary/xenia-canary/assets/111816811/63b744f5-6352-467a-bf0e-fac395700500)

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/13169122/xenia.log)

**Comment by Gliniak** [comment]
To prevent it you have to set ``ignore_offset_for_ranged_allocations`` to true, however it still might not be fully stable.

**Comment by VladOFF92** [comment]
> To prevent it you have to set `ignore_offset_for_ranged_allocations` to true, however it still might not be fully stable.

Thank you so much, it really works! Now game's working little bit slowly, but still good for playing.
