### ISSUE TITLE
4D53084D - Forza Motorsport 3: Lights and Shadows Artifacts

### ISSUE THREAD

**Issue by VladOFF92** [xenia-canary/xenia-canary#237]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [ ] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [ ] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Is it possible to fix lights and shadows artifacts in Forza Motorsport 3 (and FM 4 too)? The game runs perfectly without any glitches or freezes, but this trouble is very annoying and really spoils the appearance of graphic art.

I tried to change "gpu =" from "d3d12" to "vulkan", "query_occlusion_fake_sample_count =" from "1000" to "-1" (and back later) and disable "vsync" in xenia-canary.config, but unfortunately all this methods not helped.

### Describe what should happen

Any ideas which settings I should change in my config file? Other "Forza" games (Horizon, Horizon 2) runs without this trouble.

### If applicable, provide a callstack here, especially for crashes

![fh3_shadows](https://github.com/xenia-canary/xenia-canary/assets/111816811/22aa5138-4e68-457c-abfe-a44e5d5d0fa1)
![fh3_shadows1](https://github.com/xenia-canary/xenia-canary/assets/111816811/4c2f7254-1829-4b9e-9552-c81d28d47f03)

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/13198817/xenia.log)

**Comment by rroginela** [comment]
Hi,
 Check out https://www.reddit.com/r/ProjectForzaPlus/comments/11a4qus/welcome_to_the_project_forza_plus_sub/ to get a temp fix for some of these issue but they do not fix what causes this in Xenia... Good luck

**Comment by VladOFF92** [comment]
> Hi, Check out https://www.reddit.com/r/ProjectForzaPlus/comments/11a4qus/welcome_to_the_project_forza_plus_sub/ to get a temp fix for some of these issue but they do not fix what causes this in Xenia... Good luck

Thanks for your advice, I'll try it.

**Comment by Mungr3ss** [comment]
To hide shadow glitches in fm3, fm4 you need to edit all the track settings files and change shadow colour to 1.000000 and global specular to 0.000000
