### ISSUE TITLE
No Background Music in Spectral Force 3

### ISSUE THREAD

**Issue by gene1311** [xenia-canary/xenia-canary#240]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Background music doesn't work in Spectral Force 3.
The original game (XBOX360) have always music, but it's never played in xenia, also as in canary version.
In this game, music is very important so I'd really appreciate if this issue is cleared.

There is a sample video in youtube, linked below.
https://youtu.be/DSE3EylVXAc?si=55TyZbTni8J0G277

Thanks.

### Describe what should happen

Background Music should be always played from the start page, as the original game.

**Comment by Margen67** [comment]
Does this happen on master?

**Comment by MontyJack2020** [comment]
The sound \ music bug seems to be fixed now if you use the new sound engine.

Set "use_new_decoder = true" in the xenia-canary,config.toml file.

Tested on Xenia Canary v0a712c001 Oct 26 2024

**Comment by gene1311** [comment]
> The sound \ music bug seems to be fixed now if you use the new sound engine.
> 
> Set "use_new_decoder = true" in the xenia-canary,config.toml file.
> 
> Tested on Xenia Canary v0a712c001 Oct 26 2024

It really works well!
Thank you!

**Comment by MrPiddlesticks** [comment]
so for mine i dont get the character voices or sound effects i turned on the new decoder and im still not getting it on canary. on master i dont get the background music

**Comment by Pombaroom** [comment]
> so for mine i dont get the character voices or sound effects i turned on the new decoder and im still not getting it on canary. on master i dont get the background music

Same here. Canary from 26th of December 2025 and Master from 14th of December 2025. Both can have sound effects for a short time at the beginning, but then it is gone. Just silence.
Tried "Fake", "New", "Old", "Master" decoders - the same.
