### ISSUE TITLE
Forza Horizon 1 Crash

### ISSUE THREAD

**Issue by disturbinglysaneman** [xenia-canary/xenia-canary#245]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Forza Horizon 1 is crashing seemingly at random with the following error - no specific gameplay event triggers it, and restarting the game and playing through the same section will occasionally work fine without reproducing the error. When the error appears, the sound starts looping the last ~0.5 seconds. Game stays playable without audio until it hits a loading screen, at which point it freezes.

```
Exception encountered!
Build: canary_experimental@e7dcee4c3 on Nov 17 2023
Exception address: VCRUNTIME140.dll+1490
Stackpointer: 0x5A880FFA58
Instruction pointer: VCRUNTIME140.dll+1490
ExceptionCode: 0x3221225477 (The instruction at 0x%p
referenced memory at 0x%p. The memory could not be %s.
)
Last Win32 Error: 0x1F (A device attached to the system is not
functioning.
)
Last NTSTATUS: 0xC0000001 ({Operation Failed}
The requested operation was unsuccessful.
)
Faulting thread name: XMA Decoder (01000018)
```

My PC Specs are:
AMD 5800X3D
32GB RAM
nVidia RTX 3070
Windows 10 10.0.19045 Build 1045
Xenia Canary e7dcee4.

There are no device failures, errors or missing drivers reported in Device Manager.

### Describe what should happen

Game should play without error.

### If applicable, upload a logfile and link it here

[xenia.log.zip](https://github.com/xenia-canary/xenia-canary/files/13538388/xenia.log.zip)

**Comment by VladOFF92** [comment]
Change "mount_cache =" from "false" to "true" in xenia-canary.config

**Comment by disturbinglysaneman** [comment]
I already have. It has not fixed the issue.

**Comment by Gliniak** [comment]
You can use this build: https://github.com/xenia-canary/xenia-canary/releases/download/experimental_wip_xma_decoder/xenia_canary.zip

Audio might and probably will behave differently, but it should be more stable

**Comment by disturbinglysaneman** [comment]
Looks like that has resolved it. Cheers!
