### ISSUE TITLE
Regression in Diablo III Reaper of Souls

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [xenia-canary/xenia-canary#257]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

https://github.com/xenia-canary/xenia-canary/commit/50b42371a0bf0caad4b1aa0e6fe73892d597663a causes regression in Diablo III Reaper of Souls. 
Game may hang (not always, usual at second time) during exit from ingame to main menu. Tested several times and encountered that bug - go to ingame, press Start and choose exit, then again - go to ingame and exit to main menu. 
Commit just before that - nice. But this one - hang. 
And this last thing in log with that commit during hang - 
```
!> F8000008 BaseHeap::Alloc failed to find contiguous range
!> F8000008 Thread creation failed: C0000017
```

### Describe what should happen

Game should exit to main menu without hangs

**Comment by Gliniak** [comment]
Thanks for creating ticket. I will compare and deal with it after I will finish online stuff

**Comment by Gliniak** [comment]
Can you recheck it on latest build?

**Comment by gandalfthewhite19890404** [comment]
Yes, it is fixed now, thank you very much!
