### ISSUE TITLE
`launch_module` Config Option isn't changed with new Launch Data

### ISSUE THREAD

**Issue by ktg5** [xenia-canary/xenia-canary#262]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements

### Describe what's going wrong

To example this issue, I'll use Call of Duty Black Ops & MW2.
When loading into the main menu of each game, and if the user selects "Multiplayer", which in most Call of Duty games from this time-period split the multiplayer & possibly other modes into different modules on the game, Xenia Canary will display the following:
![xenia_canary_5iXZtdIPbp](https://github.com/xenia-canary/xenia-canary/assets/42522603/9b030377-ab3d-4ab4-ae68-ce1598e381a8)
Sometimes it'll even crash, showing:
![xenia_canary_DgwLhAWb7M](https://github.com/xenia-canary/xenia-canary/assets/42522603/2dcc051a-3d5d-420c-a942-05630cf760a8)

But after closing Xenia Canary and opening it's config, the `launch_module` string isn't set at all, thus not changing into the correct module when relaunching the same title launched before.

### Describe what should happen

What should happen is when the message about the launch data being changed is sent, Xenia Canary should write to the `launch_module` string under the user's config with the correct module name & extension.
Or even better, write to the `launch_module` string, and relaunch the emulator with the appropriate launch options (unsure if that's possible, but would be cool to not have to manually relaunch Xenia everytime :p).

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/14227973/xenia.log)

**Comment by Gliniak** [comment]
Try on this build: https://github.com/xenia-canary/xenia-canary/releases/tag/experimental_autorun_swap

It basically makes whole launch_module usage very situational and usually not required.

It will not resolve issues with error message window. These are related to some low-level shenanigans

**Comment by ktg5** [comment]
That worked! Both games I tested before now relaunch correctly.
