### ISSUE TITLE
xenia-canary.config not opening

### ISSUE THREAD

**Issue by rynhky** [xenia-canary/xenia-canary#263]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Im watching a youtube tutorial on how to emulate minecraft xbox 360 edition and it says to open the config so im no longer in the demo but when i open the config, it says "this app cant run on my pc." Does this have to do with malwarebytes or norton? I also use windows 11 so I am not sure if Xenia only works on Windows 10. Thank you!

### Describe what should happen

Config should open up

**Comment by Ivan951236** [comment]
hello,
If you are trying to open the `xenia-canary.config.toml` file, then you would need [Notepad++](https://notepad-plus-plus.org/downloads/) for it (any notepad editors but windows notepad will work), then click on "Try an app on this PC" in Open With dialog, if Notepad++ isn't in the dialog then click on "Look for another app on this PC" and search Notepad++'s Install directory, for me its `"C:\Program Files\Notepad++"` and select the notepad editor's main exe, after that follow the rest of the tutorial you followed
