### ISSUE TITLE
Xenia crashing on startup

### ISSUE THREAD

**Issue by pulentiu** [xenia-canary/xenia-canary#264]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [x] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Whenever i open the xenia_canary.exe or the xenia.exe, it shows a blackscreen (like it normally would since there's no game open) for 3 seconds and then crashes.

When Xenia Canary crashes, it gives me this error: 
![image](https://github.com/xenia-canary/xenia-canary/assets/110244963/dde3f5a8-8ae7-4b8a-9c82-ab191aec7f55)

However, when I open the regular Xenia, it just shows the blackscreen for 3 seconds, and then crashes with no error message.

My PC Specs are:
GPU: AMD Radeon RX 6700
CPU: AMD Ryzen 5 5600
RAM: 16GB 3200MHz
Xenia is installed on NVMe SSD

### Describe what should happen

Xenia and Xenia Canary should open without issues, and I should be able to open a game and play it the way it was intended

### If applicable, provide a callstack here, especially for crashes

Exception encountered!
Build: canary_experimental@97d36d6bc on Feb  7 2024
Exception address: EZFRD64.DLL+32E0
Stackpointer: 0x91629FF7B0
Instruction pointer: EZFRD64.DLL+32E0
ExceptionCode: 0x3221225477 (The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
)
Last NTSTATUS: 0xC000000D (An invalid parameter was passed to a service or function.
)
Faulting thread name:

### If applicable, upload a logfile and link it here

https://drive.google.com/file/d/1l2bVoyZ4IufVr9_Stcf6lEp_6jp_3F-5/view?usp=sharing

**Comment by Gliniak** [comment]
Not Xenia related. 
EZFRD64.DLL is controller driver that is poorly written which crashes SDL.

**Comment by pulentiu** [comment]
Thanks for the info, but do you know how I can fix it?

**Comment by pulentiu** [comment]
Thank you for helping me, I have found the controller with the poorly written driver and unplugged it from my PC, and now Xenia works again
