### ISSUE TITLE
Splatterhouse  :  Scale 3X3 Charater Very Slow + Flickering

### ISSUE THREAD

**Issue by Ryohao** [xenia-canary/xenia-canary#270]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

 Scale 3X3 Charater is Very Slow + Flickering

### Describe what should happen

Should work properly like on consoles

**Comment by Margen67** [comment]
Resolution scaling is a hack so bugs are to be expected.
