### ISSUE TITLE
Army of Two : The Bloom Effect Is Overblown + In Menus Weapons Do Not Load Properly

### ISSUE THREAD

**Issue by Ryohao** [xenia-canary/xenia-canary#274]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

The Bloom Effect Is Overblown + In Menus Weapons Do Not Load Properly

![05](https://github.com/xenia-canary/xenia-canary/assets/160484133/f084f912-e6d8-43cd-af08-d4014f95cba6)
![06](https://github.com/xenia-canary/xenia-canary/assets/160484133/4aadd8f5-960c-46dc-b24a-f65a51cd4640)

### Describe what should happen

Should work properly like on consoles

**Comment by backgamon** [comment]
Readback résolve= true solve that(for overbloom at least).
