### ISSUE TITLE
Akai katana stutter

### ISSUE THREAD

**Issue by theenemy-thd** [xenia-canary/xenia-canary#285]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

I have stuttering on the game akai katana .. I have also looked at YouTube videos of the game on xenia and the same stutter appears .. videos of it running on xb360 hw does not show this stutter. I do not get this issue on other games.

### Describe what should happen

Not sure, maybe see why this game produces stutter

**Comment by theenemy-thd** [comment]
As said above the game has a stuttering update, you can see it mostly on the background as it scrolls

**Comment by Margen67** [comment]
What are your PC specs? Does this happen on master?

**Comment by theenemy-thd** [comment]
Amd Ryzen 9 7940hs 32gb ram... AMD Radeon 780M

I downloaded canary as I had the issue with the normal one and found that it happens on both

**Comment by theenemy-thd** [comment]
So I'm gathering I have to post this issue on the master github ?
