### ISSUE TITLE
Nested exception encountered - Steam Deck

### ISSUE THREAD

**Issue by markylad** [xenia-canary/xenia-canary#286]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Every time I attempt to start a game on Steam Deck, they load and then I immediately get the message <Nested Exception Encountered> Faulting thread name: XThread0194 (F8000044) 

### Describe what should happen

The game should not crash

**Comment by Ambushfall** [comment]
I'm sorry, just browsing through this repo randomly, to come across your issue.

Mostly when opening up issues, a bit more information should be provided.

Mind giving a bit more detail about your xenia build, system, etc?

- Are you running it via Linux and Wine, what configuration, did you build it, how, which version. etc.
- Did you try doing this with the canary April 4th build?

Thanks for taking the time to read and possibly respond!

**Comment by gjc9620** [comment]
same

**Comment by gjc9620** [comment]
> I'm sorry, just browsing through this repo randomly, to come across your issue.
> 
> Mostly when opening up issues, a bit more information should be provided.
> 
> Mind giving a bit more detail about your xenia build, system, etc?
> 
> * Are you running it via Linux and Wine, what configuration, did you build it, how, which version. etc.
> * Did you try doing this with the canary April 4th build?
> 
> Thanks for taking the time to read and possibly respond!

have you solved it
