### ISSUE TITLE
Xbox 1 controllers skip 1 button in games when scrolling through them.

### ISSUE THREAD

**Issue by stefix1** [xenia-canary/xenia-canary#29]
When I play a game, like for example Minecraft, and I scroll up or down through the buttons, it skips 1 button. It is very hard to play like this and doesn't occur on Xenia Master, but that has a save problem and doesn't use patches. Please help.

**Comment by TheNewClassics** [comment]
To add to this, I only find that it happens in certain games. Both the Bomberman XBLA games do this for me using the Xbox 1 controller

**Comment by Gliniak** [comment]
I'm aware of this issue. To resolve it you can set hid in config to xinput

**Comment by Margen67** [comment]
Does this still occur?

**Comment by stefix1** [comment]
No, this does not happen anymore.
