### ISSUE TITLE
Nested Exception occurred

### ISSUE THREAD

**Issue by zarif98** [xenia-canary/xenia-canary#291]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Running any game gives me an error where it cannot find the file specified. On an unrelated note, the build also does not create any configuration file, even after creating a folder called portable.txt.
![Screenshot 2024-03-23 100120](https://github.com/xenia-canary/xenia-canary/assets/8284304/ed0c8592-71f0-445b-aec0-7e59b6197183)

### Describe what should happen

The game should launch without the error.

**Comment by Morgeon** [comment]
I launched as administrator and it worked for me.

**Comment by Gliniak** [comment]
Cannot reproduce or not easily doable in that specific moment
