### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [xenia-canary/xenia-canary#310]

**Comment by mavethee** [comment]
Rosetta doesn't expose any information about AVX support meaning whatever they support is incomplete feature set.
It's Apple's hiccup, same with RPCS3, it runs well under AVX1 CPU set in LLVM CPU, but AVX2 support is completely broken. 

![CleanShot 2024-06-12 at 18 07 19@2x](https://github.com/xenia-canary/xenia-canary/assets/47083527/89c485b3-a2a6-4335-9190-e5086c335165)

Xenia probably as RPCS3 and others will check for what CPU supports.

Rosetta doesn't give any feedback to the programs about AVX nor AVX2 at the moment, if program doesn't check for AVX and Rosetta supports expected feature set it will run, that you can see with some games tested why some work and some not.

**Comment by mavethee** [comment]
I would also check issue on original repository about Xenia for Macs instead of canary for whatever reason.
https://github.com/xenia-project/xenia/issues/596
