### ISSUE TITLE
Unhandled execution in Xenia Canary

### ISSUE THREAD

**Issue by STHPro2004** [xenia-canary/xenia-canary#321]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

When I open Xenia Canary, it displays two errors with the title "Unhandled Execution in Xenia"
I use Xenia Canary, by the way.

### Describe what should happen

The emulator normally opened, but after the latest update, it only displays the error instead.

**Comment by kadrim** [comment]
i can confirm this:

![image](https://github.com/xenia-canary/xenia-canary/assets/8304331/e561e02f-7fbf-4792-9a82-f2b18322b185)

![image](https://github.com/xenia-canary/xenia-canary/assets/8304331/4b9eafb0-3faa-4853-b69c-76a953048786)

content of logfile:

```
i> 00002DA0 Build: canary_experimental@738c8dbd1 on Jun 19 2024
i> 00002DA0 Storage root: C:\Users\***\Downloads\xenia_canary
i> 00002DA0 Content root: C:\Users\***\Downloads\xenia_canary\content
i> 00002DA0 Host cache root: C:\Users\***\Downloads\xenia_canary\cache_host
```

with an older version `canary_experimental@ff692589c on May 20 2024` this error does not occur, so the bug must be introduced somewhere between ff692589c and 738c8dbd1

**Comment by henk717** [comment]
Was introduced in [ec267c3](https://github.com/xenia-canary/xenia-canary/releases/tag/ec267c3) which is a clang update, the build right before that works for me.

**Comment by Gliniak** [comment]
Just download newest redist package: https://aka.ms/vs/17/release/vc_redist.x64.exe
