### ISSUE TITLE
 Xenia canary is not working on xbox series S ,Please help me

### ISSUE THREAD

**Issue by Azaz551** [xenia-canary/xenia-canary#327]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

If I go to xenia canary a black screen comes up and then takes me out of the emulator 

### Describe what should happen

I should be able to access the emulator because I have an xbox series S

### If applicable, upload a logfile and link it here

Uploading 74139630689__C8A1795E-1E00-4AB7-8A5D-762A309B93D9.mov…

**Comment by Margen67** [comment]
We don't support the UWP version of Xenia.
