### ISSUE TITLE
Latest commit cause Ninja Gaiden II hang when loading save.

### ISSUE THREAD

**Issue by backgamon** [xenia-canary/xenia-canary#329]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Ninja Gaiden II save working well on the previous build, now it hang at when try to load save.

### Describe what should happen

Xenia just hang.

**Comment by Gliniak** [comment]
Fixed in: https://github.com/xenia-canary/xenia-canary/commit/bd77aae7d006012e560113528f60330aa457bf0a
