### ISSUE TITLE
malware alert - versions after c4e930e_canary_experimental detected as malicious

### ISSUE THREAD

**Issue by GravityEcho** [xenia-canary/xenia-canary#330]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

malware alert - versions after c4e930e_canary_experimental detected as malicious by windows defender and others

### Describe what should happen

malware not detected because malware does not exist

### If applicable, provide a callstack here, especially for crashes

NA

### If applicable, upload a logfile and link it here

NA

**Comment by takeshineale128** [comment]
latest update is fine
