### ISSUE TITLE
Xenia crashes at startup since build ec267c3

### ISSUE THREAD

**Issue by Pipi86** [xenia-canary/xenia-canary#331]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Every build since [ec267c3](https://github.com/xenia-canary/xenia-canary/releases/tag/ec267c3) till latest, gives me a unhandled exception error. 
![Captura de pantalla (112)](https://github.com/xenia-canary/xenia-canary/assets/66808852/4b4f7d0a-2588-49dc-bb5e-8ea8db059ef8)

### Describe what should happen

It should start normally as every build before that one does.

### If applicable, upload a logfile and link it here

This is all what log file shows:
i> 00002E14 Build: canary_experimental@ec267c348 on Jun 13 2024
i> 00002E14 Storage root: C:\Program Files\Xenia
i> 00002E14 Content root: C:\Program Files\Xenia\content
i> 00002E14 Host cache root: C:\Program Files\Xenia\cache_host

**Comment by Pipi86** [comment]
My bad, i found the solution when looking at closed issues. Fix was in https://github.com/xenia-canary/xenia-canary/issues/321
Pd: Windows update sucks, it should've downloaded and installed that vc redist package automatically.

**Comment by SKK329** [comment]
I am also having the same problem.

![image](https://github.com/xenia-canary/xenia-canary/assets/117411733/cc799a26-fc57-46d1-8090-0e1e53ad81ff)


Processor	AMD Ryzen 9 7900X 12-Core Processor               4.70 GHz
Installed RAM	32.0 GB (31.2 GB usable)
GPU                 Nvidia GeForce GTX 1070
Windows 11 Home  Version 23H2

The redist package solved the problem for me as well!
