### ISSUE TITLE
545407EE - The Darkness

### ISSUE THREAD

**Issue by AndylgTom** [xenia-canary/xenia-canary#334]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Strong bloom effect problem, that made everything brighter than it should have been.

By the way, on the ps3 emulator there was the same problem, but it was fixed a long time ago.

Ver. Xenia-canary (canary_experimental@eeb96f91a on Jul 15 2024)

**Strong bloom effect**
![545407EE - 2024-07-17T01-08-47](https://github.com/user-attachments/assets/40b21779-fa4e-4486-a469-5c2e297d197c)
![545407EE - 2024-07-17T01-11-56](https://github.com/user-attachments/assets/5d42439f-4c1f-4a0c-8a69-accc5ed15bf8)

**Light shining through textures.**
![545407EE - 2024-07-17T01-49-30](https://github.com/user-attachments/assets/b19198f8-6cf3-4e7b-98fd-bb901f2f0981)
![545407EE - 2024-07-17T01-49-17](https://github.com/user-attachments/assets/cc8a9e23-69ed-422a-b40b-3e3b59e66dcd)

GIF https://i.ibb.co/QkC8HWq/Animation-1.gif

**Comment by Margen67** [comment]
Game compatibility reports don't belong here.
