### ISSUE TITLE
SpongeBob Surf & Skate stops at the loading screen

### ISSUE THREAD

**Issue by youtubeeicarlos** [xenia-canary/xenia-canary#337]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

The game starts, but on the first loading it freezes and does not continue loading.

Could you also see the possibility of including keyboard support and a function to configure controls for 2 players?

### Describe what should happen

After the loading screen, the game's initial screen should appear, a YouTube video shows the game starting on the Xbox 360 if you need a better reference

### If applicable, provide a callstack here, especially for crashes

I have no idea what this is...

### If applicable, upload a logfile and link it here

I don't know where to find the log on the emulator, but it is a visible error, starting the game on the emulator you will see the same error

**Comment by youtubeeicarlos** [comment]
@Margen67 Transformers Devastation is also crashing, it starts but in gameplay it crashes when a cutscene starts

**Comment by Margen67** [comment]
Game-specific issues belong here: https://github.com/xenia-canary/game-compatibility/
