### ISSUE TITLE
this aint an issue idk maybe it is

### ISSUE THREAD

**Issue by jcash85** [xenia-canary/xenia-canary#34]
can you get the camera part to work for as a kinect camera i got the xbox one camera and ps5 camera can you make something as to get it to work for dragon ball z kinect

**Comment by randprint** [comment]
@jcash85 go to https://discord.me/xenia-emulator for tech support or use the compatibility list for specific games https://github.com/xenia-canary/game-compatibility, stop using the issues section here like this
