### ISSUE TITLE
Setting `vsync_interval` causes instant crash since cfecdcb

### ISSUE THREAD

**Issue by svetter** [xenia-canary/xenia-canary#345]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

On builds after and at cfecdcb (which made changes to the VSync mechanism), any game I try to launch crashes instantly (before I can even see the window opening) whenever `vsync_interval` is set in the launch parameters (regardless of whether `vsync` is set to true or false).

Earlier builds do not have this problem, and it goes away when removing `vsync_interval` from the launch arguments.

### Describe what should happen

The game should launch normally.

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/user-attachments/files/16659105/xenia.log)

**Comment by Gliniak** [comment]
Maybe because there is no such option anymore?
``vsync_interval`` was replaced with ``framerate_limit``

**Comment by svetter** [comment]
Good hint 😄

Yeah that clears this up, but I will say that I didn't expect unknown parameters to lead to Canary just crashing out instead of ignoring it or an error message.
