### ISSUE TITLE
[Feature Request] DLL Injector in Xenia Canary

### ISSUE THREAD

**Issue by mrmaller1905** [xenia-canary/xenia-canary#361]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Summary:

I would like to request a feature in Xenia Canary that injects DLLs into Xbox 360 games.

### Description:

DLL injector allows players to inject custom code DLLs into Xbox 360 games to restore hashed filenames from game archives (e.g. Yeti.big of Ghost Recon Advanced Warfighter) and skip intro videos.

**Comment by AdrianCassar** [comment]
This feature is already implemented plugin docs are [here](https://github.com/AdrianCassar/game-patches/blob/plugin_docs/.github/Plugin-Docs.md).
