### ISSUE TITLE
Emulator gives error "Unhandled exception in xenia" when starting 

### ISSUE THREAD

**Issue by KlucharevTolia** [xenia-canary/xenia-canary#365]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

![изображение_2024-09-14_192231489](https://github.com/user-attachments/assets/23759b79-615e-43f7-ae56-8a86dffe1dcc)

Unhandled exception in xenia

### Describe what should happen

Work as the developer intended

**Comment by Maarcis12** [comment]
Yeah, i have the same issue.

**Comment by petran79** [comment]
Same issue too. Last commit without the error is eb785c8

**Comment by Maarcis12** [comment]
Great news, got the latest build and it now launches just fine.
