### ISSUE TITLE
Bug: Patches no work anymore

### ISSUE THREAD

**Issue by coolllman** [xenia-canary/xenia-canary#37]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Patches no work anymore on last version

### Describe what should happen

Will be fix in future version?

**Comment by Margen67** [comment]
This isn't a bug. This is due to patches now loading from `Documents\Xenia` if `portable.txt` isn't present in the same directory as `xenia.exe`.
If you want to restore the old behavior you need to create an empty text file named `portable.txt` in the same directory as `xenia.exe`.
