### ISSUE TITLE
Crash on start: 0x80000006 ({No More Files} No more files were found which match the file specification.

### ISSUE THREAD

**Issue by InterClaw** [xenia-canary/xenia-canary#375]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Since c9e85ce (and later) I'm getting the below crash on startup, regardless of game. It was working fine from d246e3b (and earlier).

![Screenshot 2024-09-23 094721](https://github.com/user-attachments/assets/18fcfc59-83ab-4292-849e-1b0982f7b2d7)

Attaching log file:
[xenia.log](https://github.com/user-attachments/files/17094289/xenia.log)

### Describe what should happen

Xenia should launch as it did with d246e3b (and earlier).

**Comment by Gliniak** [comment]
Try it on latest release. If it still happens please check if you have any custom patches that are not available on repository. It might be that broken.
If you can track it down then feel free to post it here, so I can look on what it fails

**Comment by InterClaw** [comment]
I think I was not testing the later releases properly. I can only reproduce it in c9e85ce. All later ones, including the very latest one 6a8a6d1, work fine. 👍

False alarm, sorry!
