### ISSUE TITLE
Xenia crashes while playing games

### ISSUE THREAD

**Issue by Alexey9710** [xenia-canary/xenia-canary#392]
### Validation

- [ ] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Always while trying to run a game with xenia, I got this error message. Already tried with Call Of Duty Black Ops 1 and Ninja Gaiden 2 (Note: In Ninja Gaiden 2 always happens after a video of the beginning of the chapter 3)

I should have the minimum requirements to use xenia. List of the components at the end of this Thread.
I was looking for information but I haven't find anything that could solve my problem.
Reading the message in the alert window I tried to uninstall the application (xenia) and install it again but didn't work 😢 

Thanks beforehand for tue support! 🙏 

The last time I got this error I got the following (A bit different than the one in the photo):

**This message comes from Ninja Gaiden**
```
Exception encountered! 
Build: canary_experimental@060954f0c on Oct 9 2024 
Exception address: xenia_canary.exe+406065 
Stackpointer: 0x623F9FF030 
Instruction pointer: xenia_canary.exe+406065 
ExceptionCode: 0x3221225477 (The instruction at 0x%p 
referenced memory at 0x%p. The memory could not be %s.
referenced memory at 0x%p. The memory could not be %s.
)
Last Win32 Error, 0x7E ((null)) 
Last NTSTATUS: 0xC0000135 (The code execution cannot 
proceed because %hs was not found. Reinstalling the 
program may fix this problem. 
)
Faulting thread name: GPU Commands (01000010) 
```

**This message comes from Call Of Duty Black Ops**
```
Exception encountered! 
Build: canary_experimental@5a5fe97ef on Oct 9 2024 
Exception address: xenia_canary.exe+4041CC 
Stackpointer: 0x86A3BFEF50 
Instruction pointer: xenia_canary.exe+4041CC 
ExceptionCode: 0x3221225477 (The instruction at 0x%p 
referenced memory at 0x%p. The memory could not be %s.
referenced memory at 0x%p. The memory could not be %s.
)
Last Win32 Error, 0x7E ((null)) 
Last NTSTATUS: 0xC0000135 (The code execution cannot 
proceed because %hs was not found. Reinstalling the 
program may fix this problem. 
)
Faulting thread name: GPU Commands (01000010) 
```

Components:
Ryzen 7 5700g
32 gb ram 3200 GHz DDR4
RTX 3080 MSI
850 PSU
MOBO Asus Rog B550 F

![xenia error](https://github.com/user-attachments/assets/4a787639-ec53-44a8-bee9-b8652d88a646)

### Describe what should happen

The games shouldn't crash and keep playable.

**Comment by luisfernandojti68-commits** [comment]
This message comes from FIFA 06 RTWC


Exception encountered! 
Build: canary_experimental@5a5fe97ef on Oct 9 2024 
Exception address: xenia_canary.exe+4041CC 
Stackpointer: 0x86A3BFEF50 
Instruction pointer: xenia_canary.exe+4041CC 
ExceptionCode: 0x3221225477 (The instruction at 0x%p 
referenced memory at 0x%p. The memory could not be %s.
referenced memory at 0x%p. The memory could not be %s.
)
Last Win32 Error, 0x7E ((null)) 
Last NTSTATUS: 0xC0000135 (The code execution cannot 
proceed because %hs was not found. Reinstalling the 
program may fix this problem. 
)
Faulting thread name: GPU Commands (01000010)
