### ISSUE TITLE
Custom resolution doesn't work.

### ISSUE THREAD

**Issue by nfxw** [xenia-canary/xenia-canary#397]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

The emulator crashed when you set custom resolution on latest build.
![1](https://github.com/user-attachments/assets/7b55b065-3aa2-440b-bf50-5a578cde2a72)

### Describe what should happen

-

**Comment by Margen67** [comment]
That's why #396 hasn't been merged yet. A tag being made for it is a problem with the CI.
