### ISSUE TITLE
tags/release

### ISSUE THREAD

**Issue by beyondmeat** [xenia-canary/xenia-canary#40]
There were tag changes made recently. I'm using an auto updater tool (scoop). What should it be looking at?

Fom the new tags, would this be best?

checkver: "https://github.com/xenia-canary/xenia-canary/releases/tag/experimental",
"regex": "([a-f0-9]{6})<\\/code>"
dl url: https://github.com/xenia-canary/releases/download/experimental/xenia_canary.zip

so look at the experimental (or pr) tag and use that now?
or stick with looking for canary_experimental_commitHash

**Comment by Margen67** [comment]
@beyondmeat It should be looking at `experimental` and `pr`.
