### ISSUE TITLE
[Linux/Wine only] Halo 3/Halo 3 ODST: Unimplemented IO Calls Error on game boot

### ISSUE THREAD

**Issue by Fabxx** [xenia-canary/xenia-canary#411]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

After hours of testing, and also with the help of Sowa_95, i can confirm that both games do not run at start only under Linux. 
A potential cause might be of how wine interprets the Windows paths (i.e double backslashes, character escapes etc), the logs give a Device not found error related to a DLL inside the game files, before giving the window message. 

(will provide xenia log for both windows and linux later, currently i don't have it on my system)

This issue is also persistent on steam deck.

Halo 4, Halo Wars and Halo Reach are not affected by this issue.

### Describe what should happen

It should run normally like on windows, i don't know if windows has a native dependency that is not implemented inside wine for that specific DLL in the game files. Needs some investigation.

**Comment by Margen67** [comment]
If this is a Wine/Proton specific issue it should be fixed on their side. (though I wouldn't be surprised if Xenia is doing something wrong)

**Comment by starwars1717** [comment]
it also happing on halo reach and halo 4 when tryed to those

**Comment by Fabxx** [comment]
> it also happing on halo reach and halo 4 when tryed to those

When a linux build will be available i will retest, if the issue represents itself i'll report it here. In the meantime i'll see what i can do under wine to understand this.

**Comment by starwars1717** [comment]
i mean its happening on window itself i mean

**Comment by v4u6h4n** [comment]
I have the same issue with Halo 3 on the canary linux build.
