### ISSUE TITLE
Need For Speed Pro Street 

### ISSUE THREAD

**Issue by fazed3292** [xenia-canary/xenia-canary#441]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

The car models in the always disappear when i drive over 20 km/h in the game,whether if its grip,drag,driftor speed challenges the cars always disappears including mine.When i change my view settings of the car using the "X" button im able to see a glimpse of all the cars on the track.

### Describe what should happen

The car models suppose to be visible while i drive around the track but the only thing i can see is the shadows of all the cars

**Comment by fazed3292** [comment]
![Uploading 20241201_133343.jpg…]()
![Uploading 20241201_133505.jpg…]()

**Comment by Margen67** [comment]
Does this happen on Xenia master?

**Comment by fazed3292** [comment]
> Does this happen on Xenia master?

I've only tried this on Xenia Canary 
I can't find a uwp to use for Xenia master that works

**Comment by Sebastien-Saunders** [comment]
a "friend" of mine is asking where you found a playable pro street iso, said friend is totally not me

**Comment by A1eNaz** [comment]
> a "friend" of mine is asking where you found a playable pro street iso, said friend is totally not me

yk that's illegal right.
