### ISSUE TITLE
Naruto Broken Bond Glitch 

### ISSUE THREAD

**Issue by zerr10** [xenia-canary/xenia-canary#45]

**Comment by zerr10** [comment]
> some black glitch some time.
> 
> here screen shots:
> 
> ![Glitch Naruto Broken Bond](https://user-images.githubusercontent.com/18278728/173688586-78af76c0-c6f0-42e9-b4f3-1d13a8ded0a4.jpg)

space i7 6700 3.4 Ghz RAM 8GB DDR4 2133Mhz Dual Channel Card : GTX 1070 8GB

**Comment by Margen67** [comment]
@zerr10 Does this also occur on master?

**Comment by zerr10** [comment]
@Margen67 

Yes

as for the standard version from the site:
https://xenia.jp/

but from the above side it is worse because the emulator has a disadvantage like yuzu the emulator will just sometimes turn off locks at random moments only your version from this side started working properly I do not know what you changed but the games do not close it would be useful to fix it in the yuzu emulator because suffer from a similar condition with randomly exiting the application

your version is better than the version from https://xenia.jp/

but if you ask about these black bars in the game it is in every version but yours at least doesn't close the emulator so it's better.

**Comment by zerr10** [comment]
![Naruto Broken Bond Jpg 1](https://user-images.githubusercontent.com/18278728/173907072-9426b821-8c39-43b1-9532-3e6121f02987.jpg)
![Naruto Broken Bond Jpg 2](https://user-images.githubusercontent.com/18278728/173907098-df1178a9-dc77-42d2-8cd8-990edc1216b2.jpg)
![Naruto Broken Bond Jpg 3](https://user-images.githubusercontent.com/18278728/173907108-de0b71df-8670-4e7c-9ab8-d7cdbd19c512.jpg)


another 3 photos

1 is when I turn my character towards the village, it redirects the image correctly, but as soon as I turn the camera towards the character, the image is lost, as shown in photos 2 and 3, it looks even worse than in the first post.

**Comment by Margen67** [comment]
This doesn't belong here unless it's an issue exclusive to canary.
