### ISSUE TITLE
I'm having issues with downloading Minecraft Xbox 360 edition I've done everything right but I cant seem to find the file 

### ISSUE THREAD

**Issue by AxelInu** [xenia-canary/xenia-canary#453]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

it says file not found when I try to load Minecraft I even typed out the file name only for the same result 

### Describe what should happen

the game should load to the title screen

**Comment by AxelInu** [comment]
so yall not gonna help wtf the point of having this page fr

**Comment by AxelInu** [comment]
very professional smh

**Comment by Margen67** [comment]
I made the text a little bigger so you can see it:
# THIS IS NOT A SUPPORT FORUM! For support, first read the wiki: https://github.com/xenia-canary/xenia-canary/wiki
# If your question wasn't answered there or you need help, proceed to #help in the Discord server: https://discord.gg/Q9mxZf9
