### ISSUE TITLE
Wont let me download, says canary is a virus

### ISSUE THREAD

**Issue by Sonic3Modder** [xenia-canary/xenia-canary#454]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

When I install from both the offical website and github it blocks the download saying its a virus

### Describe what should happen

It should just install

**Comment by Margen67** [comment]
It’s a false positive.

**Comment by Sonic3Modder** [comment]
what do you mean

**Comment by Sonic3Modder** [comment]
literally there is a X on the download icon saying "virus detected"

**Comment by Margen67** [comment]
This is a known issue. If it's a false positive that means it's being falsely detected and can be ignored.
