### ISSUE TITLE
Keyboard passthrough not working on Gears 1, 2, 3, Judgment

### ISSUE THREAD

**Issue by CSharpConner** [xenia-canary/xenia-canary#456]
I have the latest build on Xenia Canary which supposedly allows keyboard passthrough via `keyboard_mode = 2`
However this doesn't seem to be the case for the Gears of War series.

I managed to get the console key set to the Back button on a controller via hacking the input ini inside a Title Update.
Gears 1 --> Xe-WarInput.ini
Gears 2 --> TU__Xe-GearInput.ini
Gears 3 and Gears J --> TU__xbox360-gearinput.ini

And in those files I'd make a small entry
```
[Engine.Console]
ConsoleKey=XboxTypeS_Back
```

That part works fine for gears 1 and 2, although gears 3 and judgment won't close the console by pressing the key again, but that's not the main issue.

The main issue is typing with the keyboard yields nothing across all these games, nothing gets entered into the console prompt.
I saw some other threads talk how [Saints Row Arkham City and Arkham Origins worked](https://github.com/xenia-project/xenia/issues/2027#issuecomment-1229114469) on some way back version, but I don't have those games at the moment for Xenia Canary.

I've tried many config combinations to make this work, Ex.
```
hid = "xinput"
keyboard_mode = 2
keyboard_user_index = -1
```
But to no avail.

Can someone please confirm if keyboard passthrough is actually functional?  I honestly don't know if these games would work so it's hard to tell if that's really the problem or not.

**Comment by Gliniak** [comment]
It's only partially functional right now. 
I'm working actively to make it better and some early builds are available sometimes on Xenia discord, before I will add it to repository. You can check on these builds and if it doesn't work then feel free to share log (level 3) from such run, so I can check what is going on

**Comment by Gliniak** [comment]
Closing. It's not applicable to release versions of GoW, works correctly on debug builds

**Comment by CSharpConner** [comment]
As previously mentioned, retail release of Unreal Engine 3 x360 games don't listen for keyboard inputs.  Instead only debug/dev builds will use keyboard passthrough, a real shame but now I know.  Appreciate the effort put in, thanks Gliniak!

**Comment by preds-01** [comment]
Gears of War 2 & 3 do work with mousehook. For Gears 2, make sure you dont have any launch commands. By default it might be -nostartupmovies. This breaks mouse input for some reason. Also make sure youre launching with Mousehook and not canary. For Gears 3, some ROMS dont work with mousehook like the UK version. The world version works straight away tho. Ive also read that changing language to something other than english can break mouse input. Id suggest using Xenia Manager.

As for Gears 1, it has a native PC port so I just used that.
