### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by daviDarthemis** [xenia-canary/xenia-canary#460]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

-- Configuring done (0.1s)
CMake Error: Cannot determine link language for target "cxxopts".
CMake Error: CMake can not determine linker language for target: cxxopts
CMake Error: Cannot determine link language for target "tomlplusplus".
CMake Error: CMake can not determine linker language for target: tomlplusplus
-- Generating done (0.3s)

### Describe what should happen

.

### If applicable, provide a callstack here, especially for crashes

.

### If applicable, upload a logfile and link it here

.

**Comment by Margen67** [comment]
Xenia doesn't use CMake. Follow the building guide: https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/docs/building.md
