### ISSUE TITLE
Game crashes running on AMD Ryzen 5 5600G iGP Vega 7

### ISSUE THREAD

**Issue by liurudys30** [xenia-canary/xenia-canary#54]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

When I run the game gears of war 2 or gears of war 3 it always crashes or returns to the Windows 10 Desktop Display after selecting the campaign menu, I use AMD Ryzen 5600G iGPU vega 7

### Describe what should happen

Please update to run on AMD Ryzen 5 5600G igp vega 7

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/9205318/xenia.log)

**Comment by Margen67** [comment]
Does this happen on master?

**Comment by FabPell980** [comment]
Same issue here on Ryzen 5900HX, tested on Gears of War  judgment

**Comment by Margen67** [comment]
> Same issue here on Ryzen 5900HX, tested on Gears of War judgment

@FabPell980 Does this happen on master?

**Comment by FabPell980** [comment]
Yes, latest build
