### ISSUE TITLE
Polygon Flickering Bug (Canary Exclusive)

### ISSUE THREAD

**Issue by SpeddieSwagetti** [xenia-canary/xenia-canary#6]
The master fork has made some important commits for the D3D12 backend which fixes polygon flickering and texture corruption in some games. Current games tested are:

- Sonic Unleashed
- Sonic Generations

Merging commit: 84a8dc91e4e28e4b94dc82f75843391ba53d7904 would greatly improve these games. I understand that this is more of a request.

**Comment by randprint** [comment]
you just linked a commit that's in our repo and asked us to merge it into our repo, if I understand correctly

**Comment by SpeddieSwagetti** [comment]
*sigh... yes I do. I assumed it was referencing the other fork. The polygon flickering is absent on master but present on canary. So I'm not sure which commit actually fixed it now.

**Comment by illusion98** [comment]
It's already merged in. 🤔

**Comment by SpeddieSwagetti** [comment]
Here is a comparison of the issue:

Latest Canary Build (commit: 145870e2237c1dacb23491f6b5eb6869f476c5b1)
![Canary](https://user-images.githubusercontent.com/48142631/73235363-e68e1000-41d9-11ea-843a-b7d74cd28a41.PNG)

Master Build (commit 38bf6c88221fa724efe2accea3d61033a7ccab37)
![Master](https://user-images.githubusercontent.com/48142631/73235369-eee64b00-41d9-11ea-8bb3-e8c4d3ecc5ec.PNG)

**Comment by ZolaKluke** [comment]
Mate those are vertex explosions, they have nothing to do with what you want to merge and what you want merged is already in Canary

**Comment by SpeddieSwagetti** [comment]
I am aware, I changed the issue name
