### ISSUE TITLE
Naruto - The Broken Bond - graphical bugs

### ISSUE THREAD

**Issue by ghost** [xenia-canary/xenia-canary#63]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Hello. the game Naruto - The Broken Bond has many graphical bugs in the part of training with Jiraiya.
I noticed that the bugs seem to originate from the female NPCs in the area...

### Describe what should happen

Hello. the game Naruto - The Broken Bond has many graphical bugs in the part of training with Jiraiya.
I noticed that the bugs seem to originate from the female NPCs in the area...

### If applicable, provide a callstack here, especially for crashes

Hello. the game Naruto - The Broken Bond has many graphical bugs in the part of training with Jiraiya.
I noticed that the bugs seem to originate from the female NPCs in the area...

### If applicable, upload a logfile and link it here

Hello. the game Naruto - The Broken Bond has many graphical bugs in the part of training with Jiraiya.
I noticed that the bugs seem to originate from the female NPCs in the area...

**Comment by Margen67** [comment]
Does this happen on master?

**Comment by ghost** [comment]
> Does this happen on master?

yes
https://media.discordapp.net/attachments/837060452340203615/1012371656242647060/unknown.png?width=1202&height=676
