### ISSUE TITLE
Auto update causes crash when there's no internet connection

### ISSUE THREAD

**Issue by OverlordCW** [xenia-canary/xenia-canary#7]
[//]: # (Describe what's going wrong:)
It crashes when blocked by firewall. Maybe because of 080e1e5386a4bbe3dfe92d71053d4b1a926a1506

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by randprint** [comment]
you can set the check_update option to false in the config for now, or unblock it in your firewall, but thanks for reporting the bug.

**Comment by illusion98** [comment]
Can't reproduce on Windows 10 1909. Will update later.

**Comment by OverlordCW** [comment]
If I unblock it, it works again. I am on Windows 10 1909 and use Comodo Firewall if that makes a difference.

**Comment by Margen67** [comment]
@OverlordCW Does it do the same thing if you have no internet connection?

**Comment by LuismaSP89** [comment]
Can confirm the issue here.

@OverlordCW For me yes, Xenia crashes when I don't have internet connection.

Btw, solved by disabling the autoupdate in xenia canary config

**Comment by Margen67** [comment]
Auto updater isn't in newer builds.
