### ISSUE TITLE
Heavy sound stutter in Skate II and NBA Homecourt

### ISSUE THREAD

**Issue by Vogel88** [xenia-canary/xenia-canary#71]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

With a Xenia Version from around March 2021 (both 360 and Canary), sound, except music, worked fine, but in every version after that, background ambient and/or voices began to stutter. While the music also stuttered back then, now the background sounds to create the ambience and the voices are stuttering too. They would play back fine in the old version, so one just had to mute the music to get a nice playable game. I noticed this behaviour with Skate II and NBA Street Homecourt. The problem is gone when using the older version. Of course, this build is missing the audio delay fix and all the other improvements made over time.

### Describe what should happen

Smooth playback of voices or background sounds as in old versions of Xenia (like the one from March 24 2021)

**Comment by LuismaSP89** [comment]
The audio backend is currently being re-worked by Gliniak. The issue maybe can be solved on the near future. (1 month estimated)

**Comment by LuismaSP89** [comment]
You should test it again, there was some small changes on the audio engine wich solved some issues on different games.

**Comment by HappehLemons** [comment]
> You should test it again, there was some small changes on the audio engine wich solved some issues on different games.

Are there any more details on this fix? For example, Ninja Gaiden II has a bug with audio dropping out requiring an emulator restart. Would this have an effect, or is it targeting a different audio issue?

**Comment by EiIoGo** [comment]
i am experiencing the same issue in the simpsoms: the game (i actually have the sapnish version so i dont know if that traslates correctly) where the audio stutters, it feels like when you hold spacebar on a youtube video, if you understand what im trying to say, also my character goes invisible and his arm is black for some reason, im starting to feel like this is not the right place to put this but i dont really know where else it could go
