### ISSUE TITLE
saves not found

### ISSUE THREAD

**Issue by Datzibu** [xenia-canary/xenia-canary#72]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [ ] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [ ] This issue isn't for tech support (help with Xenia).
- [ ] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

the latest canary sep 5 build not finding saves from master build

### Describe what should happen

canary build should be finding saves from master build

**Comment by alexalc02** [comment]
xenia-canary uses portable mode by default now

just copy the content folder located in Documents\xenia\ to the same directory where you have xenia_canary.exe

**Comment by Margen67** [comment]
If you really want to revert to the old behavior you can change `portable` in the config from `true` to `false`; #68

**Comment by illusionyy** [comment]
portable is not exposed in config file, it's only command line
