### ISSUE TITLE
Xenia canary problem Video Card

### ISSUE THREAD

**Issue by kanelakis** [xenia-canary/xenia-canary#8]
Hi, I wanted to report a serious problem that happens with the emulator.
With the latest versions, at the first start, and the game starts everything is fine, but the second time after it is closed due to a game error caused by the video card, it crashes the video card and consequently the Desktop.
I updated the drivers to the latest version, with previous versions this did not happen.
Now I don't remember which was a stable version.
I currently use this version https://github.com/xenia-canary/xenia-canary/commit/378a22ae15eb7c3463c7d5b538b94be2e786c30b , but it also happens with the version of February 7 2020.

**Comment by Margen67** [comment]
Does this occur on master?

**Comment by kanelakis** [comment]
> Does this occur on master?

No,on Xenia canary.

**Comment by kanelakis** [comment]
![73991122-87539c80-494b-11ea-9dd1-f67744bf5fcf](https://user-images.githubusercontent.com/26459477/74077409-e2ef5a00-4a1f-11ea-899a-b737f826319d.png)
After this error, if I start it the second time everything crashes on the video card, and consequently Desktop and the whole pc is freezing.

**Comment by BiwwytheBoi** [comment]
That's known, you don't have to open an issue for this error.

**Comment by BiwwytheBoi** [comment]
It happens a lot

**Comment by kanelakis** [comment]
> It happens a lot

Yes I know that this error is known, the problem is not of this error, but of what happens if I start the emulator the second time, I fizz the pc and crashes the pc.

**Comment by jacob1218** [comment]
the issue he's describing is: first start game works until error, second time gpu driver crashes?

**Comment by kanelakis** [comment]
> the issue he's describing is: first start game works until error, second time gpu driver crashes?

yes

**Comment by jacob1218** [comment]
can reproduce this with GTA4
step 1: start the game until it crashes
step 2: immediately restart game
step 3: watch as the pc bluescreens, with a graphics driver/TDR error code

**Comment by kanelakis** [comment]
> can reproduce this with GTA4
> step 1: start the game until it crashes
> step 2: immediately restart game
> step 3: watch as the pc bluescreens, with a graphics driver/TDR error code

I can try this game, but the blue screen has not reached me so far, it was sparkling but then the desktop recovered.

**Comment by sprayderman** [comment]
in dark souls prepare to die something similar happens, the game starts stuttering the audio goes away then hangs up and the same graphics device error appears missing

**Comment by randprint** [comment]
This thread is riddled with assumptions and misunderstandings also Github is not a place to post to get support, if you want to follow the template to update a game in the issue tracker that has actually changed from past behaviour ie: not the graphics device lost error, you can help out development by doing that. If you want to discuss this come to our discord.
