### ISSUE TITLE
Crash loading save user profile in Earthworm Jim HD

### ISSUE THREAD

**Issue by MaLDox77** [xenia-canary/xenia-canary#83]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Only Xenia Canary can use user profiles and that functionality is necessary to start Earthworm Jim HD. 

Everything works fine starting a new game but after restarting the game and trying to continue the saved game the emulator crashes. The message related in the log seems "Alloc page count too big for requested range"

Attached the full log.

Thank you

### Describe what should happen

Using Continue in the menu must show the list of completed levels and then you can play them.

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/9763434/xenia.log)

**Comment by Margen67** [comment]
Does this still occur?

**Comment by MaLDox77** [comment]
> Does this still occur?

Yes

**Comment by r3538987** [comment]
Think this is because of XBLA profiles creation got changed at some point. And yep, this is still ongoing issue. 
https://github.com/xenia-canary/xenia-canary/issues/108

**Comment by Gliniak** [comment]
Saving/Loading issues in Earthworm Jim are related to something different than profile.

Savefile for it (FOR WHATEVER REASON) is stored in "stats". These were never implemented in any version of Xenia, but might be implemented even without profile support, however waiting for profile support might be beneficial to not introduce additional uncommon solutions

**Comment by Gliniak** [comment]
Fixed in https://github.com/xenia-canary/xenia-canary/commit/413d60bf54aa333cf0a89237f818b0cc70b8cd29

**Comment by r3538987** [comment]
> Fixed in [413d60b](https://github.com/xenia-canary/xenia-canary/commit/413d60bf54aa333cf0a89237f818b0cc70b8cd29)
If this repository doesn't allow game related issues, where issues should be opened? 
Latest builds on my side simply started to crash straight after game file drag-n-drop into executable.

**Comment by Gliniak** [comment]
> > Fixed in [413d60b](https://github.com/xenia-canary/xenia-canary/commit/413d60bf54aa333cf0a89237f818b0cc70b8cd29)
> > If this repository doesn't allow game related issues, where issues should be opened?
> > Latest builds on my side simply started to crash straight after game file drag-n-drop into executable.

Open config and set protect_zero to false (and clear_memory_page_state to true for less frustration).

![image](https://github.com/xenia-canary/xenia-canary/assets/153369/0d659c4d-3211-4611-9fe7-ca4143dd891a)
