### ISSUE TITLE
Gears of War 2 crashes after 55877f4

### ISSUE THREAD

**Issue by akrasnobaev** [xenia-canary/xenia-canary#88]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Gears of War 2 crashes on buffer overrun during scenes with radio communication (the very beginning of Act 2.4 Sinking Feeling for instance).
The following hack worked for me:

```diff
--- a/src/xenia/apu/xma_context.cc
+++ b/src/xenia/apu/xma_context.cc
@@ -656,7 +656,7 @@ void XmaContext::Decode(XMA_CONTEXT_DATA* data) {
         while (packets_skip_ > 0) {
           packets_skip_--;
           packet_idx++;
-          if (packet_idx > current_input_packet_count) {
+          if (packet_idx >= current_input_packet_count) { 
             if (!reuse_input_buffer) {
               // Last packet. Try setup once more.
               reuse_input_buffer = TrySetupNextLoop(data, true);
```

### Describe what should happen

The game should not crash.

### If applicable, provide a callstack here, especially for crashes

>	xenia_canary.exe!xe::apu::xma::GetPacketFrameOffset(unsigned char * packet) Line 30	C++ 
 	xenia_canary.exe!xe::apu::XmaContext::Decode(xe::apu::XMA_CONTEXT_DATA * data) Line 673	C++  // packet_idx == 16
 	xenia_canary.exe!xe::apu::XmaContext::Work() Line106	C++
 	xenia_canary.exe!xe::apu::XmaDecoder::WorkerThreadMain() Line 162	C++
 	xenia_canary.exe!xe::apu::XmaDecoder::Setup::__l2::<lambda>() Line 146	C++

**Comment by Gliniak** [comment]
Thanks for info. I was aware that it wasn't correct solution, however I hoped it won't affect any game in negative way. Can you share savefile? I have an idea how to resolve it, but need fast access to that location

**Comment by Gliniak** [comment]
Crashes should be resolved in commit: https://github.com/xenia-canary/xenia-canary/commit/c080e2e17ce8b2374407bc9440c480363b900cc6
